import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { createApp } from "vue";
import {
  faCalendarCheck,
  faUsers,
  faFutbol,
  faDollarSign,
  faSearch,
  faChartLine,
  faCalendarAlt,
  faCog,
  faPlus,
  faEye,
  faEdit,
  faTrash,
  faCheck,
  faTimes,
  faUserSlash,
  faUserCheck,
  faInfoCircle,
  faCalendarTimes,
  faUserPlus,
  faCreditCard,
  faMapMarkerAlt,
  faClock,
  faCamera,
  faEnvelope,
  faPhone,
  faBan,
  faArrowRight,
  faHistory,
  faHeart,
  faHeartBroken,
  faCalendarCheck,
  faStar,
  faImage,
  faUpload,
  faKey,
  faCreditCard,
  faBell,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faCalendarCheck,
  faUsers,
  faFutbol,
  faDollarSign,
  faSearch,
  faChartLine,
  faCalendarAlt,
  faCog,
  faPlus,
  faEye,
  faEdit,
  faTrash,
  faCheck,
  faTimes,
  faUserSlash,
  faUserCheck,
  faInfoCircle,
  faCalendarTimes,
  faUserPlus,
  faCreditCard,
  faMapMarkerAlt,
  faClock,
  faCamera,
  faEnvelope,
  faPhone,
  faBan,
  faArrowRight,
  faHistory,
  faHeart,
  faHeartBroken,
  faCalendarCheck,
  faStar,
  faImage,
  faUpload,
  faKey,
  faCreditCard,
  faBell
);

const app = createApp({});
app.component("font-awesome-icon", FontAwesomeIcon);
